### ISSUE TITLE
atomic system 컨벤션 제안

### ISSUE THREAD

**Issue by linear14** [hobbyloop/hobbyloop-webF#4]
### 해결하고 싶은 문제
atomic system 내부 컴포넌트 (atom / molecule / organism / template)와
tsx내에서 선언한 styled-components 혹은 atomic system 외의 컴포넌트를 구분하기 어려움

```tsx
// 어떤게 atomic system을 사용한 컴포넌트인지 한 눈에 들어오지 않음
const Component = () => {
  return (
    <Container>
      <Label>Title</Label>
      <TextInput/>
      <FooterContainer>
        <P>Footer</P>
        <SelectBox/>
      </FooterContainer>
    </Container>
  )
}
```

### 해결
`Atom.xxx` / `Molecule.xxx` 등의 네임스페이스 제공

```tsx
import { Atom, Molecule } from 'atomic-system';

const Component = () => {
  return (
    <Container>
      <Atom.Label>Title</Atom.Label>
      <Atom.TextInput/>
      <FooterContainer>
        <P>Footer</P>
        <Molecule.SelectBox/>
      </FooterContainer>
    </Container>
  )
}
```

### 추가로 얻을 수 있는 것
- Atom을 입력했을 때, Atom에 해당하는 컴포넌트들을 자동완성으로 미리 볼 수 있음

**Comment by linear14** [comment]
논의해보고 싶은 주제입니다!
만약 논의가 통과된다면 작업 해두겠습니다

**Comment by yoyongjin** [comment]
오! Atomic으로되어있는 공통 컴포넌트 적용 시에는 스타일컴포넌트와 분리도 좋고 자동완성도 활용할 수 있어서 좋네요!! 

그럼 추가적으로 스타일 컴포넌트는 html 태그를 그대로 대문자만 추가해서 쓰거나 태그명이 포함된 이름으로 하는거 어떠세요?

그리고 Atomic컴포넌트 외에 pages/기능별 폴더 안 독립적인 컴포넌트는 네이밍을 어떻게하면 좋을까요..?

**Comment by linear14** [comment]
styled component도 구분하는게 목적이면 태그명이 포함된 이름으로 하는 것 좋네요!  

>  html 태그를 그대로 대문자만 추가해서 쓰거나 태그명이 포함된 이름
요거 예시를 조금 알려주실 수 있나요?

이렇게하면 atomic components / styled components 이외의 컴포넌트들은 특별한 규칙따라 네이밍 할 필요 없어도 될 것 같다고 생각해요~ (규칙없는 네이밍의 컴포넌트들은 독립적으로 만들어둔 컴포넌트구나! 라고 생각하고 넘어가는게 가능)

**Comment by yoyongjin** [comment]
아 code block 왜저러지,,ㅎㅎ
첨써봐서 감안해서 봐주세요~

**Comment by linear14** [comment]
오 넵넵 좋습니다~!
(참고로 ``` 백틱 3개 입력하면 여러줄 코드 작성하실 수 있어요!)

```tsx
const A = styled.div`
  margin: 0;
`
```
